import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { FaTwitter, FaFacebook, FaDiscord, FaTelegram } from "react-icons/fa";
import { AiFillTwitterCircle } from "react-icons/ai";
import Link from "next/link";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero Section */}
      <div className="flex justify-between items-center  ">
        <div className="flex flex-1 flex-col p-6 md:p-12 ">
          <span className="text-[32px] md:text-[55px] text-white leading-[32px] md:leading-[55px] font-bold">
            Multichain IDO launchpad with superpowers.
          </span>
          <span className="text-[16px] md:text-[18px] mt-4 text-[#D8D8D8] leading-[24px] md:leading-[27px] font-normal">
            3swap launchpad will empower crypto currency projects with the
            ability to distribute tokens and raise liquidity.
          </span>
          <button className="bg-[#FFD549] mt-4 p-2 w-[177.53px] md:w-[241.64px] ">
            <span className="font-bold text-black text-[16px] md:text-[20px] leading-[16px] md:leading-[20px]">
              See projects
            </span>
          </button>
          <span className="font-bold text-[20px] md:text-[24px] leading-[20px] md:leading-[24px] mt-6 text-white">
            Our partners
          </span>
          <div className="flex justify-start gap-4 mt-4 items-center">
            <Image src="/white 1.svg" width={75} height={75} alt="5ire logo" />
            <Image
              src="/Bitgert.svg"
              width={75}
              height={75}
              alt="Bitgert logo"
            />
          </div>
        </div>
        <Image
          className="hidden md:flex flex-1"
          src="/hero.png"
          width={962.17}
          height={962.65}
          alt="hero image"
        />
      </div>
      {/* Hero Section Ends */}

      {/* About us section */}
      <div className="md:flex  justify-between p-6 md:p-12 items-center">
        <div className="flex flex-col">
          <span className="font-bold text-[#FFD549] text-[20px] mb-4 leading-[20px] ">
            About us
          </span>
          <span className="font-bold  text-white text-[32px] md:text-[55px] mb-4 leading-[32px] md:leading-[70px] ">
            Super charge your project for a sucessful launch.
          </span>
          <span className="font-normal text-[#D8D8D8] mb-4 text-[16px] md:text-[18px] leading-[24px] md:leading-[27px] ">
            3swap launchpad will empower crypto currency projects with the
            ability to distribute tokens and raise liquidity. 3swap launchpad
            will empower crypto currency projects with the ability to distribute
            tokens and raise liquidity.
          </span>
          <div className="flex justify-start items-center gap-2">
            <Link href="/">
              <span className="text-white font-bold text-[30px] ">
                <AiFillTwitterCircle />
              </span>
            </Link>

            <Link href="/">
              <span className="text-white font-bold text-[30px] ">
                <FaFacebook />
              </span>
            </Link>

            <span className="bg-white text-[#350870] rounded-full p-[3px] font-bold text-[26px] ">
              <Link href="/">
                <FaDiscord />
              </Link>
            </span>
            <Link href="/">
              <span className="text-white font-bold text-[30px] ">
                <FaTelegram />
              </span>
            </Link>
          </div>
        </div>

        <div className="border-2 bg-[#7e7ba0] md:mt-o mt-6 bg-opacity-50 rounded-3xl">
          <div className="flex flex-col p-6 md:p-12">
            <span className="font-bold mb-4 text-white text-[28px] leading-[28px] ">
              Why choose us?
            </span>
            <span className="font-normal mb-4 text-white text-opacity-50 text-[16px] leading-[32px] ">
              lorem Ipsum is simply dummy text of the printing dummy text
              of.lorem Ipsum is simply dummy text of the printing dummy text
              of.lorem Ipsum is simply dummy text of the printing dummy text of.
            </span>
            <div className="md:flex  justify-between items-center md:mb-4 text-white">
              <Link href="/">
                <span className="flex justify-start mb-2 md:mb-0 gap-2 items-center">
                  Read whitepaper
                  <Image
                    src="/ei.svg"
                    alt="external link"
                    width={25}
                    height={25}
                  />
                </span>
              </Link>
              <Link href="/">
                <span className="flex justify-start mb-2 md:mb-0 gap-2 items-center">
                  how to buy
                  <Image
                    src="/ei.svg"
                    alt="external link"
                    width={25}
                    height={25}
                  />
                </span>
              </Link>
            </div>
            <div className="md:flex  justify-between items-center text-white">
              <Link href="/">
                <span className="flex justify-start mb-2 md:mb-0 gap-2 items-center">
                  Apply for IDO
                  <Image
                    src="/ei.svg"
                    alt="external link"
                    width={25}
                    height={25}
                  />
                </span>
              </Link>
              <Link href="/">
                <span className="flex justify-start gap-2 items-center">
                  Launchpad token
                  <Image
                    src="/ei.svg"
                    alt="external link"
                    width={25}
                    height={25}
                  />
                </span>
              </Link>
            </div>
          </div>
        </div>
      </div>
      {/* About us section ends */}

      {/* Live sales section */}
      <div className="p-6 md:p-12">
        <div className="flex justify-between items-center mb-6">
          <span className="font-bold text-[16px] md:text-[32px] leading-[16px] md:leading-[32px] text-white ">
            Live sales
          </span>
          <button className="bg-black hidden md:block p-3">
            <span className="font-bold text-[14px] leading-[14px] text-white">
              <Link href="/listing">View more Listing</Link>
            </span>
          </button>
        </div>

        <div className="flex justify-between items-center">
          <Link href="/presail">
            <Image src="/frieght.png" alt="freight" width={525} height={445} />
          </Link>
          <Link href="/presail">
            <Image
              className="hidden md:block"
              src="/devil.png"
              alt="freight"
              width={525}
              height={445}
            />
          </Link>
        </div>
        <button className="bg-black md:hidden p-3 mt-6 w-[244px] ">
          <span className="font-bold text-[14px] leading-[14px] text-white">
            <Link href="/listing">View more Listing</Link>
          </span>
        </button>
      </div>
      {/* Live sales section ends */}
    </div>
  );
}
